---
title: "BaBart_Superscript"
author: "David Eleveld s1741225"
date: "25-8-2022"
output: pdf_document
---

# Setup

## Packages

```{r Packages, include=FALSE}
library("haven")
library("dbarts")
library("glmertree")
library("dplyr")
library("here")
library("multilevel")
library("tidyverse")
library("LongCART")
library("reshape2")
library("rempsyc")
library("readr")
library("stats")
library("ggsignif")
library("sjlabelled")
library("rstatix")
library("jtools")
library("Hmisc")
library("ggstatsplot")
```

## Data generation functions

```{r}
## Bayesian data generation function
## Returns X_gen, y_gen
gendata_bay <- function(data, PPD, n_gen){
  
  if(nrow(data) != ncol(PPD)){stop("Amount of observations in PPD is different from data")}
  
  index_gen <- sample.int(n = nrow(data), size = n_gen, replace = TRUE)
  x_gen <- data[index_gen,]
  y_gen <- sapply(index_gen, function(i) sample(x = PPD[,i], size = 1))
  
  return(cbind(x_gen, y_gen))
}


## Smearing data generation function
## Returns X_gen only
gendata_smr <- function(data, palt = 0.5, n_gen, keeps = NaN){

  if(palt < 0 | palt > 1){stop("palt must be bound between between 0 and 1")}
  
  index_gen <- sample.int(n = nrow(data), size = n_gen, replace = TRUE)
  gen_data <- data[index_gen,]
  
  if(palt != 0){
    for(i in 1:nrow(gen_data)){
      
      for(j in 1:ncol(gen_data)){
        
        if(names(gen_data[,j]) %in% keeps){next} # keeps cluster structure
        
        if(runif(1) <= palt){gen_data[i,j] <- sample(x = as.matrix(data[,j]), size = 1)}
      }
    }
  }
  
  return(gen_data)
}
```

## parameters

```{r}
nfolds <- 10
nreps <- 10
ngensizes <- c(1,5,10)
palts <- c(0, 0.25, 0.5)
BaSmear_design <- expand.grid(ngensizes, palts)
```

# Clustered Datasets

## Safety data (N=1000)

```{r Safety data}
set.seed(42)
data = read_sav(file.path(here(),"Project David","Safety.sav"))

# ## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=",
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))
tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("street")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(unsafe ~ 1 | (1|street) | age + sex + economic + crowded,
                     data = traindat)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$unsafe - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(unsafe ~ age + sex + economic + crowded,
       data = traindat, group.by = traindat$street,
       test = testdat, group.by.test = testdat$street,
       combineChains = TRUE, seed = 42, verbose = FALSE)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$unsafe - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ 1 | (1|street) | age + sex + economic + crowded,
                        data = surr_mlbart,
                        weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$unsafe - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ 1 | (1|street) | age + sex + economic + crowded,
        #                   data = surr_mlbart)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$unsafe - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR NOG WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("street"))

          Mbart <- rbart_vi(unsafe ~ age + sex + economic + crowded,
                             data = surr_mlbart, group.by = surr_mlbart$street,
                             combineChains = TRUE, seed = 42, verbose = FALSE)
          
          y_gen <- Mbart$yhat.train.mean
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1 | (1|street) | age + sex + economic + crowded,
                          data = surr_mlbart,
                          weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$unsafe - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1 | (1|street) | age + sex + economic + crowded,
          #                  data = surr_mlbart)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$unsafe - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "Safety_MSE.txt")
write.csv(x = tree_size, file = "Safety_TreeSize.txt")
```

## ACT data (N=1000)

```{r ACT data}
set.seed(42)
data(ACTG175)
## Remove missings
ACTG175 <- ACTG175[!is.na(ACTG175$cd4), ]
sapply(data, class)

## Correct coding of factors
ACTG175$pidnum <- factor(ACTG175$pidnum) 
ACTG175$hemo <- factor(ACTG175$hemo) 
ACTG175$homo <- factor(ACTG175$homo)
ACTG175$drugs <- factor(ACTG175$drugs)
ACTG175$oprior <- factor(ACTG175$oprior)
ACTG175$z30 <- factor(ACTG175$z30)
ACTG175$zprior <- factor(ACTG175$zprior)
ACTG175$race <- factor(ACTG175$race)
ACTG175$str2 <- factor(ACTG175$str2)
ACTG175$symptom <- factor(ACTG175$symptom)
ACTG175$treat <- factor(ACTG175$treat)
ACTG175$offtrt <- factor(ACTG175$offtrt)

data <- ACTG175[ACTG175$pidnum %in% sample(x = unique(ACTG175$pidnum), size = 377),]
rm(ACTG175)

# ## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=", 
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))
tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("pidnum")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(cd4 ~ time | (1 | pidnum) | gender + wtkg + hemo + homo +
                          drugs + karnof + oprior + z30 + zprior + race + str2 +
                          symptom + treat + offtrt, 
                        data = traindat, cluster = pidnum)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$cd4 - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(cd4 ~ time + gender + wtkg + hemo + homo + drugs +
                          karnof + oprior + z30 + zprior + race + str2 +
                          symptom + treat + offtrt,
                        data = traindat, group.by = traindat$pidnum,
                        test = testdat, group.by.test = testdat$pidnum,
                      combineChains = TRUE, seed = 42)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$cd4 - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ time | (1 | pidnum) | gender + wtkg + hemo +
                               homo + drugs + karnof + oprior + z30 + zprior + 
                               race + str2 + symptom + treat + offtrt,
                             cluster = pidnum, data = surr_mlbart,
                             weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$cd4 - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ time | (1 | pidnum) | gender + wtkg + hemo +
        #                        homo + drugs + karnof + oprior + z30 + zprior + 
        #                        race + str2 + symptom + treat + offtrt,
        #                      cluster = pidnum, data = surr_mlbart,
        #                      maxdepth = 5)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$cd4 - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("pidnum"))

          Mbart <- rbart_vi(cd4 ~ time + gender + wtkg + hemo + homo + drugs +
                          karnof + oprior + z30 + zprior + race + str2 +
                          symptom + treat + offtrt,
                        data = surr_mlbart, group.by = surr_mlbart$pidnum,
                        combineChains = TRUE,
                        seed = 42)
          
          y_gen <- Mbart$yhat.train.mean
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ time | (1 | pidnum) | gender + wtkg + hemo +
                               homo + drugs + karnof + oprior + z30 + zprior + 
                               race + str2 + symptom + treat + offtrt,
                             cluster = pidnum, data = surr_mlbart,
                             weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$cd4 - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ time | (1 | pidnum) | gender + wtkg + hemo +
          #                      homo + drugs + karnof + oprior + z30 + zprior + 
          #                      race + str2 + symptom + treat + offtrt,
          #                    cluster = pidnum, data = surr_mlbart,
          #                    maxdepth = 5)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$cd4 - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "ACT_MSE.txt")
write.csv(x = tree_size, file = "ACT_TreeSize.txt")
```

## ECLSK kids
### math (N=1000)

```{r}
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Math ability data.Rdata"))
data <- mathdata[mathdata$CHILDID %in% sample(x = unique(mathdata$CHILDID), size = 200),]
sapply(X = data, FUN = class)
table(data$RACE)
data$CHILDID <- factor(data$CHILDID)
rm(mathdata)

## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=",
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))


tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("CHILDID","RACE")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(score ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = traindat)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$score - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
         data = traindat, group.by = traindat$CHILDID,
         test = testdat, group.by.test = testdat$CHILDID,
         combineChains = TRUE, seed = 42)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$score - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = surr_mlbart,
                      weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$score - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
        #               C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
        #               P1FIRKDG + AGEBASELINE, data = surr_mlbart)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$score - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR NOG WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("CHILDID"))
          
          # Dit klopt toch niet?? ik snap het iig niet
          # Mbart <- rbart_vi(score ~ months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #             C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #             P1FIRKDG + AGEBASELINE,  
          #             data = traindat, test = surr_mlbart, group.by = CHILDID,
          #             verbose = FALSE, combineChains = TRUE)
          #
          # y_gen <- colMeans(brt$yhat.test)
          # surr_dat <- cbind(surr_dat, y_gen)
          
                    
          Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
                       data = surr_mlbart, group.by = surr_mlbart$CHILDID,
                       keepTrees = TRUE, combineChains = TRUE, seed = 42)
          
          y_gen <- Mbart$yhat.train.mean
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                          C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                          P1FIRKDG + AGEBASELINE,
                        data = surr_mlbart, weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$score - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #                 C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #                 P1FIRKDG + AGEBASELINE, cluster = CHILDID,
          #               data = surr_mlbart)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$score - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "ECLSKmath_MSE.txt")
write.csv(x = tree_size, file = "ECLSKmath_TreeSize.txt")
```

### reading (N=1000)

```{r}
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Reading ability data.Rdata"))
data <- readdata[readdata$CHILDID %in% sample(x = unique(readdata$CHILDID), size = 200),]
data$asmtmm <- factor(data$asmtmm)
data$CHILDID <- factor(data$CHILDID)
rm(readdata)

## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=",
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))

tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("CHILDID","RACE")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(score ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = traindat)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$score - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
         data = traindat, group.by = traindat$CHILDID,
         test = testdat, group.by.test = testdat$CHILDID,
         combineChains = TRUE, seed = 42)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$score - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = surr_mlbart,
                      weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$score - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
        #               C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
        #               P1FIRKDG + AGEBASELINE, data = surr_mlbart)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$score - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR NOG WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("CHILDID"))
          
          # Dit klopt toch niet?? ik snap het iig niet
          # Mbart <- rbart_vi(score ~ months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #             C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #             P1FIRKDG + AGEBASELINE,  
          #             data = traindat, test = surr_mlbart, group.by = CHILDID,
          #             verbose = FALSE, combineChains = TRUE)
          #
          # y_gen <- colMeans(brt$yhat.test)
          # surr_dat <- cbind(surr_dat, y_gen)
          
                    
          Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
                       data = surr_mlbart, group.by = surr_mlbart$CHILDID,
                       keepTrees = TRUE, combineChains = TRUE, seed = 42)
          
          y_gen <- Mbart$yhat.train.mean
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                          C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                          P1FIRKDG + AGEBASELINE,
                        data = surr_mlbart, weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$score - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #                 C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #                 P1FIRKDG + AGEBASELINE, cluster = CHILDID,
          #               data = surr_mlbart)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$score - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "ECLSKreading_MSE.txt")
write.csv(x = tree_size, file = "ECLSKreading_TreeSize.txt")
```

### science (N=999)

```{r}
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Science ability data.Rdata"))
data <- sciedata[sciedata$CHILDID %in% sample(x = unique(sciedata$CHILDID), size = 333),]
data$asmtmm <- as.factor(data$asmtmm)
rm(sciedata)

# ## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=",
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))

tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("CHILDID","RACE")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(score ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = traindat)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$score - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
         data = traindat, group.by = traindat$CHILDID,
         test = testdat, group.by.test = testdat$CHILDID,
         combineChains = TRUE, seed = 42)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$score - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                      C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                      P1FIRKDG + AGEBASELINE, data = surr_mlbart,
                      weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$score - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
        #               C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
        #               P1FIRKDG + AGEBASELINE, data = surr_mlbart)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$score - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR NOG WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("CHILDID"))
          
          # Dit klopt toch niet?? ik snap het iig niet
          # Mbart <- rbart_vi(score ~ months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #             C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #             P1FIRKDG + AGEBASELINE,  
          #             data = traindat, test = surr_mlbart, group.by = CHILDID,
          #             verbose = FALSE, combineChains = TRUE)
          #
          # y_gen <- colMeans(brt$yhat.test)
          # surr_dat <- cbind(surr_dat, y_gen)
          
                    
          Mbart <- rbart_vi(score ~ GENDER + RACE + WKSESL + C1GMOTOR + C1FMOTOR + 
                          T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + P1FIRKDG + 
                          AGEBASELINE + months,
                       data = surr_mlbart, group.by = surr_mlbart$CHILDID,
                       keepTrees = TRUE, combineChains = TRUE, seed = 42)
          
          y_gen <- Mbart$yhat.train.mean
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
                          C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
                          P1FIRKDG + AGEBASELINE,
                        data = surr_mlbart, weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$score - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1 | (1|CHILDID) | months + GENDER + RACE + WKSESL + C1GMOTOR + 
          #                 C1FMOTOR + T1INTERN + T1EXTERN + T1INTERP + T1CONTRO + 
          #                 P1FIRKDG + AGEBASELINE, cluster = CHILDID,
          #               data = surr_mlbart)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$score - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "ECLSKscience_MSE.txt")
write.csv(x = tree_size, file = "ECLSKscience_TreeSize.txt")

```

## ECLSK School (N = 999) DOES NOT CONVERGE

```{r}
set.seed(42)
load(file = "ECLSK_school.Rda")
Data <- Data %>%
  group_by(school_ID) %>%
  mutate(school_read = mean(as.numeric(child_read))) %>% 
  ungroup()
#Data <- Data[Data$school_ID %in% sort(unique(Data$school_ID))[table(Data$school_ID) >= 10],]
data <- Data[Data$school_ID %in% sample(x = unique(Data$school_ID), size = 146),]
data$school_ID <- factor(data$school_ID)
rm(Data)
data <- as.data.frame(data)

# ## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=", 
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))
tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("school_ID")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(child_readscore ~ 1| (1|school_ID) |  school_pct.male +
                            school_SES  + school_race + school_cert + school_read,
                          data = traindat, verbose = FALSE)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0)

    MSE[(k-1)*10+i,1] <- mean((testdat$child_readscore - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(child_readscore ~ school_pct.male + school_SES +
                          school_race + school_cert + school_read,
                        data = traindat, group.by = traindat$school_ID,
                        test = testdat, group.by.test = testdat$school_ID,
                        combineChains = TRUE, seed = 42, verbose = FALSE)

    posterior <- Mbart$yhat.train

    MSE[(k-1)*10+i,2] <- mean((testdat$child_readscore - Mbart$yhat.test.mean)^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(traindat, posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~ 1| (1|school_ID) |  school_pct.male +
                            school_SES  + school_race + school_cert + school_read,
                             data = surr_mlbart, verbose = FALSE, cluster = school_ID,
                             weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$child_readscore - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~ 1| (1|school_ID) |  school_pct.male +
        #                     school_SES  + school_race + school_cert + school_read,
        #                      data = surr_mlbart, maxdepth = 5)
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$child_readscore - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR NOG WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("school_ID"))

          Mbart <- rbart_vi(child_readscore ~ school_pct.male + school_SES +
                          school_race + school_cert + school_read,
                        data = surr_mlbart, group.by = surr_mlbart$school_ID,
                        combineChains = TRUE, verbose = FALSE,
                        seed = 42)
          
          y_gen <- Mbart$yhat.train.mean
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1| (1|school_ID) |  school_pct.male +
                               school_SES  + school_race + school_cert + school_read,
                            data = surr_mlbart, verbose = FALSE, cluster = school_ID,
                            weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$child_readscore - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1| (1|school_ID) |  school_pct.male +
          #                   school_SES  + school_race + school_cert + school_read,
          #                 data = surr_mlbart, maxdepth = 5)
          # 
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$child_readscore - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "ECLSKschool_MSE.txt")
write.csv(x = tree_size, file = "ECLSKschool_TreeSize.txt")
```

## Marriage (N=1000) Binominal ieks

```{r}
set.seed(42)
load("practical6_surveydata.Rda")

data <- g
data <- na.omit(data)
data$marriage_01 <- as.numeric(data$marriage)
data$marriage <- factor(data$marriage)
data <- data[sample(x = 1:nrow(data), size = 1000 , replace = F),]
rm(g)

# ## Create objects for saving results
tree_size <- MSE <- as.data.frame(matrix(data = NA, 
                                         nrow = nfolds*nreps, 
                                         ncol = 3 + 
                                           length(ngensizes) +
                                           nrow(BaSmear_design) + 
                                           length(ngensizes[ngensizes != 1]) +
                                           nrow(BaSmear_design[!(BaSmear_design[,1] %in% 1),])))
colnames(tree_size) <- colnames(MSE) <- c("GLMM_tree", "Bart", "BA",
                                          paste0("BaBart_N*",ngensizes), 
                                          paste0("Smearing_N*",BaSmear_design[,1], "_palt=",BaSmear_design[,2]),
                                          paste0("BaBart_N*", ngensizes[ngensizes != 1], "_Nw"),
                                          paste0("Smearing_N*",BaSmear_design[!(BaSmear_design[,1] %in% 1),][,1], "_palt=", 
                                                 BaSmear_design[!(BaSmear_design[,1] %in% 1),][,2], "_Nw"))
tel <- 0
system.time(
for (k in 1:nreps){
  
  # Generate train-test splits
  fold_ids <- sample(rep(1:nfolds, times = ceiling(nrow(data)/nfolds)), 
                     size = nrow(data), replace = FALSE)

  for (i in 1:nfolds){
    
    # train-test split
    traindat <- data[fold_ids != i, ]
    testdat <- data[fold_ids == i, ]
    
    # Check whether all factor levels in test are also in train, else omit from test
    for (fact in c("state")) {
      levs <- unique(testdat[ , fact]) %in% unique(traindat[ , fact])
      if (!all(levs)) {
        traindat <- rbind(traindat, 
                          testdat[which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ])
        testdat <- testdat[-which(!testdat[ , fact] %in% unique(testdat[ , fact])[levs]), ]
        print(paste0("Levels of fold ", i, " omitted from test data: ", 
                             unique(testdat[ , fact])[!levs]))
      }
    }
    
    ###### Fit a regualar GLMM tree ######
    glmtree <- lmertree(marriage_01 ~ 1 | (1|state) | female + age_cat + edu_cat + 
                      p_evang + kerry_04, data = traindat)

    pred_glmtree <- predict(glmtree, newdata = testdat, re.form = ~0, type = "response")

    MSE[(k-1)*10+i,1] <- mean((testdat$marriage_01 - pred_glmtree)^2)
    tree_size[(k-1)*10+i,1] <- (length(glmtree$tree)-1)/2

    ######  fit multilevel BART ######
    Mbart <- rbart_vi(marriage_01 ~ female + age_cat + edu_cat + p_evang + kerry_04, 
                        data = traindat, group.by = traindat$state,
                        test = testdat, group.by.test = testdat$state,
                      combineChains = TRUE, seed = 42)

    posterior <- binomial()$linkinv((Mbart$yhat.train))

    MSE[(k-1)*10+i,2] <- mean((testdat$marriage_01 - binomial()$linkinv(colMeans(Mbart$yhat.test)))^2)

    # fit BaBart GLMM trees with different sizes of Ngen using Baygen and smearing
      for(ngen in ngensizes){
        
        # Bayesian data generation
        surr_mlbart <- gendata_bay(as_tibble(traindat), posterior, ngen * nrow(traindat))

        ###### Baygen Weighted ######
        babart <- lmertree(y_gen ~1 | (1|state) | female + age_cat + edu_cat + 
                          p_evang + kerry_04, data = surr_mlbart,
                      weights = rep(1/ngen, times = nrow(surr_mlbart)))
        
        pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        MSE[(k-1)*10+i,3+match(ngen,ngensizes)] <- mean((testdat$marriage_01 - pred_babart)^2)
        tree_size[(k-1)*10+i,3+match(ngen,ngensizes)] <- (length(babart$tree)-1)/2

        # ###### Baygen NOT Weighted ######
        # if(ngen != 1){
        #   babart <- lmertree(y_gen ~1 | (1|state) | female + age_cat + edu_cat + 
        #                   p_evang + kerry_04, data = surr_mlbart,
        #               weights = rep(1/ngen, times = nrow(surr_mlbart)))
        # 
        #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
        #   MSE[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- mean((testdat$marriage_01 - pred_babart)^2)# :s
        #   tree_size[(k-1)*10+i,2+match(ngen,ngensizes)+length(ngensizes)+nrow(BaSmear_design)] <- (length(babart$tree)-1)/2
        # }

        # smearing HIER MOET DE CLUSTERSTRUCTUUR WORDEN BEHOUDEN
        for(palt in palts){
          surr_mlbart <- gendata_smr(as_tibble(traindat), palt, ngen * nrow(traindat), keeps = c("state"))
          
          Mbart <- rbart_vi(marriage_01 ~ female + age_cat + edu_cat + p_evang + kerry_04,  
                      data = traindat, test = surr_mlbart, group.by = traindat$state,
                      group.by.test = surr_mlbart$state, verbose = FALSE,
                      combineChains = TRUE, seed = 42)
          
          y_gen <- binomial()$linkinv(colMeans(Mbart$yhat.test))
          
          surr_mlbart <- cbind(surr_mlbart, y_gen)

          ###### Smearing Weighted ######
          babart <- lmertree(y_gen ~ 1 | (1|state) | female + age_cat + edu_cat + p_evang + kerry_04, 
                        data = surr_mlbart, weights = rep(1/ngen, times = nrow(surr_mlbart)))
          
          pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          MSE[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- mean((testdat$marriage_01 - pred_babart)^2)
          tree_size[(k-1)*10+i,3+length(ngensizes)+match(ngen,ngensizes)+(match(palt, palts)-1)*length(ngensizes)] <- (length(babart$tree)-1)/2

          # ##### Smearing NOT Weighted ######
          # if(ngen != 1){
          #   babart <- lmertree(y_gen ~ 1 | (1|state) | female + age_cat + edu_cat + p_evang + kerry_04, 
          #               data = surr_mlbart)
          #   
          #   pred_babart <- predict(babart, newdata = testdat, re.form = ~0)
          #   MSE      [(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- mean((testdat$marriage_01 - pred_babart)^2)
          #   tree_size[(k-1)*10+i,2+length(ngensizes)*2+nrow(BaSmear_design)+(match(palt, palts)-1)*(length(ngensizes)-1)+match(ngen, ngensizes)-1] <- (length(babart$tree)-1)/2
          # }
        }
      }
    tel <- tel + 1
    print(paste0("[",round((tel)/(nreps*nfolds)*100),"%]"))
  }
}
)

write.csv(x = MSE, file = "marriage_MSE.txt")
write.csv(x = tree_size, file = "marriage_TreeSize.txt")
```

# Make plots

```{r}
rm(list = ls())

# lees data in
Safety_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "Safety_MSE.txt", header = TRUE, sep = ",", row.names = 1))
Safety_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "Safety_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))

ACT_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "ACT_MSE.txt", header = TRUE, sep = ",", row.names = 1))
ACT_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "ACT_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))

ECLSKmath_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKmath_MSE.txt", header = TRUE, sep = ",", row.names = 1))
ECLSKmath_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKmath_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))

ECLSKreading_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKreading_MSE.txt", header = TRUE, sep = ",", row.names = 1))
ECLSKreading_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKreading_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))

ECLSKscience_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKscience_MSE.txt", header = TRUE, sep = ",", row.names = 1))[,1:14]
ECLSKscience_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKscience_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))[,1:13]

ECLSKschool_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKschool_MSE.txt", header = TRUE, sep = ",", row.names = 1))
ECLSKschool_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "ECLSKschool_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))

marriage_MSE <- Filter(function(x)!all(is.na(x)), read.table(file = "marriage_MSE.txt", header = TRUE, sep = ",", row.names = 1))
marriage_TreeSize <- Filter(function(x)!all(is.na(x)), read.table(file = "marriage_TreeSize.txt", header = TRUE, sep = ",", row.names = 1))


# combine all MSE datasets
MSEsets <- mget(grep(x = ls(), pattern = "MSE", value = TRUE))
allMSE <- do.call("rbind", MSEsets)

# combine all MSE datasets
TreeSizesets <- mget(grep(x = ls(), pattern = "TreeSize", value = TRUE)) 
allTreeSize <- do.call("rbind", TreeSizesets)

# # plot relative MSE's
# relMSE <- apply(X = allMSE, MARGIN = 1, FUN = function(x){x/min(x)})
# relMSElong <- melt(relMSE)
# colnames(relMSElong) <- c("Model", "Dataset", "MSE")
# relMSElong$Dataset <- gsub("_MSE\\.[0-9]+", "", relMSElong$Dataset)
# relMSElong$Dataset <- as.factor(relMSElong$Dataset)
# 
# ggplot(relMSElong, aes(x=Dataset, y=MSE, fill=Model)) + 
#   geom_boxplot() +
#   facet_wrap(~Dataset, scales = "free", nrow = 1) +
#   theme(axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Relative MSE for every Dataset")
# 
# ggplot(relMSElong, aes(x=MSE, y=Model, fill=Model)) + 
#   geom_boxplot() +
#   labs(x = "MSE / min(MSE)") +
#   theme(legend.position = "none",
#         axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Figure 4: Relative MSE combined")

# plot absolute MSE's
allMSElong <- melt(as.matrix(allMSE))
allMSElong$Var3 <- allMSElong$Var1
allMSElong$Var1 <- allMSElong$Var2
allMSElong$Var2 <- allMSElong$Var3
allMSElong$Var3 <- allMSElong$niks
colnames(allMSElong) <- c("Model", "Dataset", "MSE")
allMSElong$Dataset <- gsub("_MSE\\.[0-9]+", "", allMSElong$Dataset)
allMSElong$Dataset <- as.factor(allMSElong$Dataset)

# ggplot(allMSElong, aes(x=Model, y=MSE, fill=Model)) + 
#     geom_boxplot() +
#     facet_wrap(~Dataset, scales = "free", nrow = 1) +
#   theme(axis.text.x=element_blank(),
#         axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Figure 3: Absolute MSE for every dataset")

# plot absolte TreeSize
allTreeSizelong <- melt(as.matrix(allTreeSize))
allTreeSizelong$Var3 <- allTreeSizelong$Var1
allTreeSizelong$Var1 <- allTreeSizelong$Var2
allTreeSizelong$Var2 <- allTreeSizelong$Var3
allTreeSizelong$Var3 <- allTreeSizelong$niks
colnames(allTreeSizelong) <- c("Model", "Dataset", "Tree Size")
allTreeSizelong$Dataset <- gsub("_TreeSize\\.[0-9]+", "", allTreeSizelong$Dataset)
allTreeSizelong$Dataset <- as.factor(allTreeSizelong$Dataset)

# ggplot(allTreeSizelong, aes(x=`Tree Size`, y=Model, fill=Model)) + 
#   geom_boxplot() +
#   theme(legend.position = "none",
#         axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Figure 2: Tree Size combined")

ggplot(allTreeSizelong, aes(x=Model, y=`Tree Size`, fill=Model)) + 
    geom_boxplot() +
    facet_wrap(~Dataset, scales = "free", nrow = 2) +
  theme(axis.text.x=element_blank(),
        axis.title=element_text(size=14,face="bold"),
        axis.text=element_text(size=12),
        legend.text=element_text(size=12),
        legend.title=element_text(size=14,face="bold"),
        legend.position = c(0.82,0.25),
        plot.title=element_text(size=18,face="bold")) +
  ggtitle("Figure 1: Tree Size for every dataset")

levels(allTreeSizelong$Model) <- c("GLMM tree", "PPD: N=1", "PPD: N=5", "PPD: N=10", "smearing: N=1, palt=0.00", "smearing: N=5, palt=0.00", "smearing: N=10, palt=0.00", "smearing: N=1, palt=0.25", "smearing: N=5, palt=0.25", "smearing: N=10, palt=0.25", "smearing: N=1, palt=0.50", "smearing: N=5, palt=0.50", "smearing: N=10, palt=0.50")

# # plot relative TreeSize
# relTreeSize <- apply(X = allTreeSize, MARGIN = 1, FUN = function(x){x/min(x)})
# relTreeSizelong <- melt(relTreeSize)
# colnames(relTreeSizelong) <- c("Model", "Dataset", "Tree Size")
# relTreeSizelong$Dataset <- gsub("_TreeSize\\.[0-9]+", "", relTreeSizelong$Dataset)
# relTreeSizelong$Dataset <- as.factor(relTreeSizelong$Dataset)
# 
# ggplot(relTreeSizelong, aes(x=`Tree Size`, y=Model, fill=Model)) + 
#   geom_boxplot() +
#   theme(legend.position = "none",
#         axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Relative Tree Size combined")
# 
# ggplot(relTreeSizelong, aes(x=Model, y=`Tree Size`, fill=Model)) + 
#     geom_boxplot() +
#     facet_wrap(~Dataset, scales = "free", nrow = 1) +
#   theme(axis.text.x=element_blank(),
#         axis.title=element_text(size=14,face="bold"),
#         axis.text=element_text(size=12),
#         legend.text=element_text(size=12),
#         legend.title=element_text(size=14,face="bold"),
#         plot.title=element_text(size=18,face="bold")) +
#   ggtitle("Figure 1: Relative Tree Size for every dataset")

############ calculate variance for every dataset ############

### safety ###
set.seed(42)
data = read_sav(file.path(here(),"Project David","Safety.sav"))
var_safety <- var(data$unsafe)

### ACT ###
set.seed(42)
data(ACTG175)
## Remove missings
ACTG175 <- ACTG175[!is.na(ACTG175$cd4), ]
sapply(data, class)

## Correct coding of factors
ACTG175$pidnum <- factor(ACTG175$pidnum) 
ACTG175$hemo <- factor(ACTG175$hemo) 
ACTG175$homo <- factor(ACTG175$homo)
ACTG175$drugs <- factor(ACTG175$drugs)
ACTG175$oprior <- factor(ACTG175$oprior)
ACTG175$z30 <- factor(ACTG175$z30)
ACTG175$zprior <- factor(ACTG175$zprior)
ACTG175$race <- factor(ACTG175$race)
ACTG175$str2 <- factor(ACTG175$str2)
ACTG175$symptom <- factor(ACTG175$symptom)
ACTG175$treat <- factor(ACTG175$treat)
ACTG175$offtrt <- factor(ACTG175$offtrt)

data <- ACTG175[ACTG175$pidnum %in% sample(x = unique(ACTG175$pidnum), size = 377),]
rm(ACTG175)
var_ACT <- var(data$cd4)

### math ###
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Math ability data.Rdata"))
data <- mathdata[mathdata$CHILDID %in% sample(x = unique(mathdata$CHILDID), size = 200),]
sapply(X = data, FUN = class)
table(data$RACE)
data$CHILDID <- factor(data$CHILDID)
rm(mathdata)

var_math <- var(data$score)

### reading ###
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Reading ability data.Rdata"))
data <- readdata[readdata$CHILDID %in% sample(x = unique(readdata$CHILDID), size = 200),]
data$asmtmm <- factor(data$asmtmm)
data$CHILDID <- factor(data$CHILDID)
rm(readdata)

var_reading <- var(data$score)

### science ###
set.seed(42)
load(file.path(here(),"Project David","ECLSK","Science ability data.Rdata"))
data <- sciedata[sciedata$CHILDID %in% sample(x = unique(sciedata$CHILDID), size = 333),]
data$asmtmm <- as.factor(data$asmtmm)
rm(sciedata)

var_science <- var(data$score)

### school ###
set.seed(42)
load(file = "ECLSK_school.Rda")
Data <- Data %>%
  group_by(school_ID) %>%
  mutate(school_read = mean(as.numeric(child_read))) %>% 
  ungroup()
#Data <- Data[Data$school_ID %in% sort(unique(Data$school_ID))[table(Data$school_ID) >= 10],]
data <- Data[Data$school_ID %in% sample(x = unique(Data$school_ID), size = 146),]
data$school_ID <- factor(data$school_ID)
rm(Data)
data <- as.data.frame(data)

var_school <- var(data$child_readscore)

### marriage ###
set.seed(42)
load("practical6_surveydata.Rda")

data <- g
data <- na.omit(data)
data$marriage_01 <- as.numeric(data$marriage)
data$marriage <- factor(data$marriage)
data <- data[sample(x = 1:nrow(data), size = 1000 , replace = F),]
rm(g)

var_marriage <- var(data$marriage_01)

rm(data)

# add to long dataset
allMSElong$Variance <- NA
allMSElong$Variance[(allMSElong$Dataset == "ACT")] <- var_ACT
allMSElong$Variance[(allMSElong$Dataset == "ECLSKmath")] <- var_math
allMSElong$Variance[(allMSElong$Dataset == "ECLSKreading")] <- var_reading
allMSElong$Variance[(allMSElong$Dataset == "ECLSKschool")] <- var_school
allMSElong$Variance[(allMSElong$Dataset == "ECLSKscience")] <- var_science
allMSElong$Variance[(allMSElong$Dataset == "marriage")] <- var_marriage
allMSElong$Variance[(allMSElong$Dataset == "Safety")] <- var_safety

allMSElong$Rsquared <- 1 - allMSElong$MSE / allMSElong$Variance

levels(allMSElong$Model) <- c("GLMM tree","BART", "PPD: N=1", "PPD: N=5", "PPD: N=10", "smearing: N=1, palt=0.00", "smearing: N=5, palt=0.00", "smearing: N=10, palt=0.00", "smearing: N=1, palt=0.25", "smearing: N=5, palt=0.25", "smearing: N=10, palt=0.25", "smearing: N=1, palt=0.50", "smearing: N=5, palt=0.50", "smearing: N=10, palt=0.50")

# plot combined Rsquared
ggplot(allMSElong, aes(x=Rsquared, y=Model, fill=Model)) + 
  geom_boxplot() +
  labs(x = "MSE / variance(y) a.k.a. Rsquared") +
  theme(legend.position = "none",
        axis.title=element_text(size=14,face="bold"),
        axis.text=element_text(size=12),
        legend.text=element_text(size=12),
        legend.title=element_text(size=14,face="bold"),
        plot.title=element_text(size=18,face="bold")) +
  ggtitle(expression(R^2~" combined"))

ggplot(allMSElong, aes(x=Dataset, y=Rsquared, fill=Model)) + 
  geom_boxplot() +
  facet_wrap(~Dataset, scales = "free_x", nrow = 2) +
  theme(axis.title=element_text(size=14,face="bold"),
        axis.text=element_text(size=12),
        legend.text=element_text(size=12),
        legend.title=element_text(size=14,face="bold"),
        legend.position = c(0.82,0.25),
        plot.title=element_text(size=18,face="bold")) +
  ylab(expression(R^2)) +
  ggtitle(expression(R^2~" for every dataset"))


ggplot(allMSElong[allMSElong$Dataset == "marriage",], aes(x=Rsquared, y=Model)) + 
  scale_y_discrete(limits = rev(levels(allMSElong$Model))) +
  geom_violin() +
  theme_apa() +
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange") +
  xlab(expression(R^2)) +
  ggtitle(expression(R^2 ~ " for every model on Marriage dataset"))

ggplot(allMSElong[allMSElong$Dataset == "ECLSKschool",], aes(x=Rsquared, y=Model)) + 
  scale_y_discrete(limits = rev(levels(allMSElong$Model))) +
  geom_violin() +
  theme_apa() +
  stat_summary(fun.data = "mean_cl_boot", geom = "pointrange") +
  xlab(expression(R^2)) +
  ggtitle(expression(R^2 ~ " for every model on ECLSKscience dataset"))
```


# Statistical analyses

```{r}
# data preperation T_T
{
  # finds the highest Rsq for every dataset, and calculates mean.
  Rsquared_best_means <- allMSElong %>%
    dplyr::group_by(Model, Dataset) %>% 
    dplyr::mutate(Rsquared.Mean = mean(Rsquared), Rsquared.SD = sd(Rsquared)) %>% 
    dplyr::ungroup() %>%
    dplyr::select(Model, Dataset, Rsquared.Mean, Rsquared.SD) %>% 
    dplyr::distinct() %>% 
    dplyr::mutate(dummy_Model = substr(Model, 1,3)) %>% 
    dplyr::group_by(Dataset, dummy_Model) %>% 
    dplyr::top_n(1, Rsquared.Mean) %>% 
    dplyr::ungroup() %>% 
    dplyr::select(Model, Dataset, Rsquared.Mean, Rsquared.SD) %>% 
    dplyr::arrange(Dataset)
  
  # for every highest Rsq model, add every value of Rsq to the row
  Rsquared_empty <- as.data.frame(matrix(NA, nrow = nrow(Rsquared_best_means), ncol = 100))
  for(i in 1:nrow(Rsquared_best_means)){
    tempRsquareds <- (allMSElong) %>%  
      dplyr::select(Model, Dataset, Rsquared) %>% 
      dplyr::filter(Model == as.character(sjlabelled::to_character(Rsquared_best_means[i,1])) & Dataset == as.character(to_character(Rsquared_best_means[i,2]))) %>% 
      dplyr::select(Rsquared) %>% 
      t() %>% 
      as_vector()
    Rsquared_empty[i,] <- tempRsquareds
  }
  Rsquared_best_total <- cbind(Rsquared_best_means, Rsquared_empty)
}


# statistical tests: ANOVA
ANOVA_list <- Rsquared_best_total %>% 
  dplyr::select(-Rsquared.Mean, -Rsquared.SD) %>% 
  split(f = .$Dataset) %>% 
  map(~ (.) %>% dplyr::select(-Dataset) %>%
        stats::reshape(varying = c(2:101), v.names = "Rsquared", idvar = "Model", timevar = "fold", direction = "long") %>% 
        stats::aov(formula = Rsquared ~ Model) %>% 
        summary
      )

# statistical tests: Tukey
tukey_list <- Rsquared_best_total %>% 
  dplyr::select(-Rsquared.Mean, -Rsquared.SD) %>% 
  split(f = .$Dataset) %>% 
  map(~ (.) %>% dplyr::select(-Dataset) %>%
        stats::reshape(varying = c(2:101), v.names = "Rsquared", idvar = "Model", timevar = "fold", direction = "long") %>% 
        rstatix::tukey_hsd(formula = Rsquared ~ Model) %>% 
        dplyr::mutate(contrast = paste0(.$group1,"---",.$group2),
                      contrast = str_split(contrast, "---"))
      )


# boxplots with tukey tests (i just found out ggbetweenstats is better)
plot_list <- Rsquared_best_total %>% 
  dplyr::select(-Rsquared.Mean, -Rsquared.SD) %>% 
  split(f = .$Dataset) %>% 
  imap(~ (.x) %>% dplyr::select(-Dataset) %>%
         stats::reshape(varying = c(2:101), v.names = "Rsquared", idvar = "Model", timevar = "fold", direction = "long") %>%
         ggplot(., aes(x = Model, y = Rsquared)) +
           geom_boxplot() +
           theme_apa() +
           ggtitle(label = .y) +
             geom_signif(
             comparisons = tukey_list[[.y]]$contrast, # hier zou je kunnen aanvragen om alleen glmm met ppd en smearing te doen (of misschien in Tukey test)
             y_position = seq(from = max(.x[,3:102])+0.02, to = (max(.x[,3:102]) + (max(.x[,3:102]) - min(.x[,3:102]))/2), length.out = 6),
             annotations = tukey_list[[.y]]$p.adj.signif
          )
  )

test <- Rsquared_best_total %>% 
  dplyr::select(-Rsquared.Mean, -Rsquared.SD) %>% 
  split(f = .$Dataset) %>% 
  map(~ (.) %>% dplyr::select(-Dataset) %>%
        stats::reshape(varying = c(2:101), v.names = "Rsquared", idvar = "Model", timevar = "fold", direction = "long")
      )


# boxplots with tukey tests (i just found out ggbetweenstats is better)
plot_list2 <- Rsquared_best_total %>% 
  dplyr::select(-Rsquared.Mean, -Rsquared.SD) %>% 
  split(f = .$Dataset) %>% 
  imap(~ (.x) %>% dplyr::select(-Dataset) %>%
         stats::reshape(varying = c(2:101), v.names = "Rsquared", idvar = "Model", timevar = "fold", direction = "long") %>%
         ggbetweenstats(
          data = .,
          x = Model,
          y = Rsquared,
          type = "parametric", # ANOVA or Kruskal-Wallis
          var.equal = TRUE, # ANOVA or Welch ANOVA
          plot.type = "box",
          pairwise.comparisons = TRUE,
          pairwise.display = "significant",
          centrality.plotting = FALSE,
          bf.message = FALSE,
          ggtheme = theme_apa()
        )
  )

####################### cool tree size plots ---- N
TS1 <- allTreeSize %>% 
  pivot_longer(cols = c("BaBart_N.1", "BaBart_N.5", "BaBart_N.10")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("BaBart_N.1", "BaBart_N.5", "BaBart_N.10")) %>% 
                  recode_factor(BaBart_N.1 = "N = 1", BaBart_N.5 = "N = 5", BaBart_N.10 = "N = 10"),
                `Tree Size` = value,
                Model = factor("PPD sampling")) %>% 
  dplyr::select(`Generated Sample Size`, `Tree Size`, Model) 
  
TS2 <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.1_palt.0", "Smearing_N.5_palt.0", "Smearing_N.10_palt.0")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("Smearing_N.1_palt.0", "Smearing_N.5_palt.0", "Smearing_N.10_palt.0")) %>% 
                  recode_factor(Smearing_N.1_palt.0 = "N = 1", Smearing_N.5_palt.0 = "N = 5", Smearing_N.10_palt.0 = "N = 10"),
                `Tree Size` = value,
                Model = factor("Smearing: palt = 0")) %>% 
  dplyr::select(`Generated Sample Size`, `Tree Size`, Model) 

TS3 <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.1_palt.0.25", "Smearing_N.5_palt.0.25", "Smearing_N.10_palt.0.25")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("Smearing_N.1_palt.0.25", "Smearing_N.5_palt.0.25", "Smearing_N.10_palt.0.25")) %>% 
                  recode_factor(Smearing_N.1_palt.0.25 = "N = 1", Smearing_N.5_palt.0.25 = "N = 5", Smearing_N.10_palt.0.25 = "N = 10"),
                `Tree Size` = value,
                Model = factor("Smearing: palt = .25")) %>% 
  dplyr::select(`Generated Sample Size`, `Tree Size`, Model) 

TS4 <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.1_palt.0.5", "Smearing_N.5_palt.0.5", "Smearing_N.10_palt.0.5")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("Smearing_N.1_palt.0.5", "Smearing_N.5_palt.0.5", "Smearing_N.10_palt.0.5")) %>% 
                  recode_factor(Smearing_N.1_palt.0.5 = "N = 1", Smearing_N.5_palt.0.5 = "N = 5", Smearing_N.10_palt.0.5 = "N = 10"),
                `Tree Size` = value,
                Model = factor("Smearing: palt = .50")) %>% 
  dplyr::select(`Generated Sample Size`, `Tree Size`, Model) 


treesizeplot_grouped <- (bind_rows(TS1, TS2, TS3, TS4)) %>% 
  grouped_ggwithinstats(x=`Generated Sample Size`, y = `Tree Size`,
                type = "np", pairwise.display = "significant",
                grouping.var = Model)

treesizeplot_combined <- (bind_rows(TS1, TS2, TS3, TS4)) %>% 
  ggwithinstats(x=`Generated Sample Size`, y = `Tree Size`,
                type = "np", pairwise.display = "significant")


########################## cool Rsq plots ----- N
allRsquaredwide <- allMSElong %>% 
  dplyr::mutate(fold = rep(1:100,98)) %>% 
  dplyr::select(Model, Dataset, Rsquared, fold) %>% 
  split(f = .$Dataset) %>% 
  map(~ (.) %>% pivot_wider(names_from = Model, values_from = Rsquared)) %>%
  bind_rows()
colnames(allRsquaredwide)

RS1 <- allRsquaredwide %>% 
  pivot_longer(cols = c(`PPD: N=1`, `PPD: N=5`, `PPD: N=10`)) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("PPD: N=1", "PPD: N=5", "PPD: N=10")) %>% 
                  recode_factor("PPD: N=1" = "N = 1", "PPD: N=5" = "N = 5", "PPD: N=10" = "N = 10"),
                Rsquared = value,
                Model = factor("PPD sampling")) %>% 
  dplyr::select(`Generated Sample Size`, Rsquared, Model) 
  
RS2 <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=1, palt=0.00", "smearing: N=5, palt=0.00", "smearing: N=10, palt=0.00")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("smearing: N=1, palt=0.00", "smearing: N=5, palt=0.00", "smearing: N=10, palt=0.00")) %>% 
                  recode_factor(`smearing: N=1, palt=0.00` = "N = 1", `smearing: N=5, palt=0.00` = "N = 5", `smearing: N=10, palt=0.00` = "N = 10"),
                Rsquared = value,
                Model = factor("Smearing: palt = 0")) %>% 
  dplyr::select(`Generated Sample Size`, Rsquared, Model) 

RS3 <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=1, palt=0.25", "smearing: N=5, palt=0.25", "smearing: N=10, palt=0.25")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("smearing: N=1, palt=0.25", "smearing: N=5, palt=0.25", "smearing: N=10, palt=0.25")) %>% 
                  recode_factor(`smearing: N=1, palt=0.25` = "N = 1", `smearing: N=5, palt=0.25` = "N = 5", `smearing: N=10, palt=0.25` = "N = 10"),
                Rsquared = value,
                Model = factor("Smearing: palt = .25")) %>% 
  dplyr::select(`Generated Sample Size`, Rsquared, Model) 

RS4 <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=1, palt=0.50", "smearing: N=5, palt=0.50", "smearing: N=10, palt=0.50")) %>% 
  dplyr::mutate(`Generated Sample Size` = factor(name, levels = c("smearing: N=1, palt=0.50", "smearing: N=5, palt=0.50", "smearing: N=10, palt=0.50")) %>% 
                  recode_factor(`smearing: N=1, palt=0.50` = "N = 1", `smearing: N=5, palt=0.50` = "N = 5", `smearing: N=10, palt=0.50` = "N = 10"),
                Rsquared = value,
                Model = factor("Smearing: palt = .50")) %>% 
  dplyr::select(`Generated Sample Size`, Rsquared, Model)


Rsquaredplot_grouped <- (bind_rows(RS1, RS2, RS3, RS4)) %>% 
  grouped_ggwithinstats(x=`Generated Sample Size`, y = Rsquared,
                type = "np", pairwise.display = "significant",
                grouping.var = Model)

Rsquaredplot_combined <- (bind_rows(RS1, RS2, RS3, RS4)) %>% 
  ggwithinstats(x=`Generated Sample Size`, y = Rsquared,
                type = "np", pairwise.display = "significant",
                pointpath = TRUE)


########################## cool Tree Size plots ----- palt
TS2palt <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.1_palt.0", "Smearing_N.1_palt.0.25", "Smearing_N.1_palt.0.5")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(Smearing_N.1_palt.0 = "Palt = 0.00",Smearing_N.1_palt.0.25 = "Palt = 0.25", Smearing_N.1_palt.0.5 = "Palt = 0.50"),
                `Tree Size` = value,
                Model = factor("Smearing: N = 1")) %>% 
  dplyr::select(Palt, `Tree Size`, Model)

TS3palt <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.5_palt.0", "Smearing_N.5_palt.0.25","Smearing_N.5_palt.0.5")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(Smearing_N.5_palt.0 = "Palt = 0.00",Smearing_N.5_palt.0.25 = "Palt = 0.25", Smearing_N.5_palt.0.5 = "Palt = 0.50"),
                `Tree Size` = value,
                Model = factor("Smearing: N = 5")) %>% 
  dplyr::select(Palt, `Tree Size`, Model) 

TS4palt <- allTreeSize %>% 
  pivot_longer(cols = c("Smearing_N.10_palt.0", "Smearing_N.10_palt.0.25" , "Smearing_N.10_palt.0.5")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(Smearing_N.10_palt.0 = "Palt = 0.00",Smearing_N.10_palt.0.25 = "Palt = 0.25", Smearing_N.10_palt.0.5 = "Palt = 0.50"),
                `Tree Size` = value,
                Model = factor("Smearing: N = 10")) %>% 
  dplyr::select(Palt, `Tree Size`, Model) 

treesizeplot_grouped_palt <- (bind_rows(TS2palt, TS3palt, TS4palt)) %>% 
  grouped_ggwithinstats(x=Palt, y = `Tree Size`,
                type = "np", pairwise.display = "significant",
                grouping.var = Model)

treesizeplot_combined_palt <- (bind_rows(TS2palt, TS3palt, TS4palt)) %>% 
  ggwithinstats(x=Palt, y = `Tree Size`,
                type = "np", pairwise.display = "significant")


########################## cool Rsq plots ----- palt
RS2palt <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=1, palt=0.00", "smearing: N=1, palt=0.25", "smearing: N=1, palt=0.50")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(`smearing: N=1, palt=0.00` = "Palt = 0.00", `smearing: N=1, palt=0.25` = "Palt = 0.25", `smearing: N=1, palt=0.50` = "Palt = 0.50"),
                Rsquared = value,
                Model = factor("Smearing: N = 1")) %>% 
  dplyr::select(Palt, Rsquared, Model)

RS3palt <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=5, palt=0.00", "smearing: N=5, palt=0.25","smearing: N=5, palt=0.50")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(`smearing: N=5, palt=0.00` = "Palt = 0.00", `smearing: N=5, palt=0.25` = "Palt = 0.25", `smearing: N=5, palt=0.50` = "Palt = 0.50"),
                Rsquared = value,
                Model = factor("Smearing: N = 5")) %>% 
  dplyr::select(Palt, Rsquared, Model) 

RS4palt <- allRsquaredwide %>% 
  pivot_longer(cols = c("smearing: N=10, palt=0.00", "smearing: N=10, palt=0.25" , "smearing: N=10, palt=0.50")) %>% 
  dplyr::mutate(Palt = factor(name) %>% 
                  recode_factor(`smearing: N=10, palt=0.00` = "Palt = 0.00", `smearing: N=10, palt=0.25` = "Palt = 0.25", `smearing: N=10, palt=0.50` = "Palt = 0.50"),
                Rsquared = value,
                Model = factor("Smearing: N = 10")) %>% 
  dplyr::select(Palt, Rsquared, Model) 

Rsquaredplot_grouped_palt <- (bind_rows(RS2palt, RS3palt, RS4palt)) %>% 
  grouped_ggwithinstats(x=Palt, y = Rsquared,
                type = "np", pairwise.display = "significant",
                grouping.var = Model)

Rsquaredplot_combined_palt <- (bind_rows(RS2palt, RS3palt, RS4palt)) %>% 
  ggwithinstats(x=Palt, y = Rsquared,
                type = "np", pairwise.display = "significant")


save(list = c("plot_list",
              "plot_list2",
              "treesizeplot_grouped",
              "treesizeplot_combined",
              "Rsquaredplot_grouped",
              "Rsquaredplot_combined",
              "treesizeplot_grouped_palt",
              "treesizeplot_combined_palt",
              "Rsquaredplot_grouped_palt",
              "Rsquaredplot_combined_palt"),
     file = "coolplots.RData")

(bind_rows(RS1, RS2, RS3, RS4)) %>% 
  grouped_ggbetweenstats(x=`Generated Sample Size`, y = Rsquared,
                grouping.var = Model) &
    geom_hline(yintercept = mean(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
    annotate("text", x = 0.6, y = mean(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC") &
    geom_hline(yintercept = mean(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
    annotate("text", x = 0.6, y = mean(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")

(bind_rows(RS1, RS2, RS3, RS4)) %>% 
  ggwithinstats(x=`Generated Sample Size`, y = Rsquared,
                type = "np", pairwise.display = "significant",
                centrality.type = "parametric") &
  geom_hline(yintercept = mean(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = mean(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC") &
  geom_hline(yintercept = mean(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
  annotate("text", x = 0.6, y = mean(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")

(bind_rows(RS1, RS2, RS3, RS4)) %>% 
  ggbetweenstats(x=`Generated Sample Size`, y = Rsquared) &
    geom_hline(yintercept = mean(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
    annotate("text", x = 0.6, y = mean(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC") &
    geom_hline(yintercept = mean(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
    annotate("text", x = 0.6, y = mean(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")
```

# Make Tables

```{r}
# Mean and SD Tree Sizes
table1 <- allTreeSizelong %>% 
  group_by(Model, Dataset) %>% 
  summarise(M = mean(`Tree Size`), SD = round(sd(`Tree Size`), digits = 2)) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = Dataset,
    names_glue = "{Dataset}.{.value}",
    values_from = c(M, SD)
  ) %>% 
  dplyr::select(Model, order(names(.))) 

table1 %>% nice_table(., separate.header = TRUE, italics = seq(.),
             title = c("Mean tree size and standard deviation","Table 1"))

# Mean and SD MSE
table2 <- allMSElong %>% 
  group_by(Model, Dataset) %>% 
  summarise(M = mean(Rsquared), SD = round(sd(Rsquared), digits = 2)) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = Dataset,
    names_glue = "{Dataset}.{.value}",
    values_from = c(M, SD)
  ) %>% 
  dplyr::select(Model, order(names(.)))

table2 %>% nice_table(., separate.header = TRUE, italics = seq(.),
             title = c("Rsquared and standard deviation","Table 2"))


```

```{r}
load("coolplots.Rdata")

plot_list
plot_list2

Rsquaredplot_grouped &
  geom_hline(yintercept = median(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = 1.5, parse = TRUE, color = "#0000CC") &
  geom_hline(yintercept = median(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")
Rsquaredplot_combined &
  geom_hline(yintercept = median(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = 1.5, parse = TRUE, color = "#0000CC") &
  geom_hline(yintercept = median(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")

Rsquaredplot_grouped_palt &
  geom_hline(yintercept = median(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = 1.5, parse = TRUE, color = "#0000CC") &
  geom_hline(yintercept = median(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")
Rsquaredplot_combined_palt &
  geom_hline(yintercept = median(allRsquaredwide$`GLMM tree`), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$`GLMM tree`), label = "italic(`GLMM`)", vjust = 1.5, parse = TRUE, color = "#0000CC") &
  geom_hline(yintercept = median(allRsquaredwide$BART), linetype = "dashed", color = "#FF0000") &
  annotate("text", x = 0.6, y = median(allRsquaredwide$BART), label = "italic(`BART`)", vjust = -0.5, parse = TRUE, color = "#FF0000")

treesizeplot_grouped &
  geom_hline(yintercept = median(allTreeSize$GLMM_tree), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allTreeSize$GLMM_tree), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC")
treesizeplot_combined &
  geom_hline(yintercept = median(allTreeSize$GLMM_tree), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allTreeSize$GLMM_tree), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC")

treesizeplot_grouped_palt &
  geom_hline(yintercept = median(allTreeSize$GLMM_tree), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allTreeSize$GLMM_tree), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC")
treesizeplot_combined_palt &
  geom_hline(yintercept = median(allTreeSize$GLMM_tree), linetype = "dashed", color = "#0000CC") &
  annotate("text", x = 0.6, y = median(allTreeSize$GLMM_tree), label = "italic(`GLMM`)", vjust = -0.5, parse = TRUE, color = "#0000CC")
```

