---
title: "Plots"
author: "David Eleveld s1741225"
date: "25-6-2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("here")
library("tidyverse")
library("Hmisc")
library("ggpubr")
```


```{r Safety}
course <- "Safety"

# Baysian + Weighted
MSE_saf_bay_w <- read.csv(file.path(here(),"Project David","safety",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_saf_bay_w <- read.csv(file.path(here(),"Project David","safety",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_saf_bay <- read.csv(file.path(here(),"Project David","safety",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_saf_bay <- read.csv(file.path(here(),"Project David","safety",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_saf_smr_w <- read.csv(file.path(here(),"Project David","safety",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_saf_smr_w <- read.csv(file.path(here(),"Project David","safety",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_saf_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_saf_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_saf_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_saf_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_saf_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_saf_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_saf_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_saf_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_saf_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_saf_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_saf_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_saf_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))


tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))

# # Weighted
# MSE_saf_bay_w <- read.csv(file.path(here(),"Project David","safety","MSE_Safety_baygen[1,5,10]_weighted"), header = TRUE, row.names = 1)
# TS_saf_bay_w <- read.csv(file.path(here(),"Project David","safety","TreeSize_Safety_baygen[1,5,10]_weighted"), header = TRUE, row.names = 1)

# # not weighted
# MSE_saf <- read.csv(file.path(here(),"Project David","safety","MSE_Safety_baygen[1,5,10]_"), header = TRUE, row.names = 1)
# TS_saf <- read.csv(file.path(here(),"Project David","safety","TreeSize_Safety_baygen[1,5,10]_"), header = TRUE, row.names = 1)
```

```{r ECLSK_science}
course <- "Science"

# Baysian + Weighted
MSE_sci_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_sci_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_sci_bay <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_sci_bay <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_sci_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_sci_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","science",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_sci_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_sci_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_sci_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_sci_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_sci_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_sci_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_sci_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_sci_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_sci_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_sci_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_sci_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_sci_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))
```

```{r ECLSK_reading}
course <- "Reading"

# Baysian + Weighted
MSE_rd_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_rd_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_rd_bay <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_rd_bay <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_rd_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_rd_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_rd_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_rd_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_rd_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_rd_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_rd_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_rd_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))
```


```{r ECLSK_math}
course <- "Math"

# Baysian + Weighted
MSE_mth_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_mth_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_mth_bay <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_mth_bay <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_mth_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_mth_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","math",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_mth_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_mth_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_mth_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_mth_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_mth_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_mth_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_mth_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_mth_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_mth_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_mth_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_mth_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_mth_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))
```
```{r ACT}
course <- "ACT"

# Baysian + Weighted
MSE_act_bay_w <- read.csv(file.path(here(),"Project David","ACT",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_act_bay_w <- read.csv(file.path(here(),"Project David","ACT",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_act_bay <- read.csv(file.path(here(),"Project David","ACT",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_act_bay <- read.csv(file.path(here(),"Project David","ACT",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_act_smr_w <- read.csv(file.path(here(),"Project David","ACT",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_act_smr_w <- read.csv(file.path(here(),"Project David","ACT",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_act_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_act_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_act_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_act_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_act_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_act_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_act_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_act_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_act_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_act_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_act_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_act_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))
```


```{r}
course <- "Reading"
# Baysian + NOT Weighted
MSE_rd_bay <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_rd_bay <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_rd_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_rd_smr_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_rd_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_rd_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_rd_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_rd_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_rd_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_rd_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_rd_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_rd_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))


# 
# # Baysian + Weighted
# MSE_rd_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("MSE_",course,"_baygen[1,5,10]_weighted_newform")), header = TRUE, row.names = 1)
# TS_rd_bay_w <- read.csv(file.path(here(),"Project David","ECLSK","reading",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted_newform")), header = TRUE, row.names = 1)
# MSE2 <- MSE_rd_bay_w
# tree_size2 <- TS_rd_bay_w
# 
# 
# apply(X = MSE, MARGIN = 2, FUN = mean)
# apply(X = MSE, MARGIN = 2, FUN = sd)
# apply(X = tree_size, MARGIN = 2, FUN = mean)
# apply(X = tree_size, MARGIN = 2, FUN = sd)
# 
# # MSE_long <- MSE %>% gather(key = "Method", value = "MSE")
# # MSE_long$Method <- as.factor(MSE_long$Method)
# par(mar = c(7.1, 4.1, 4.1, 2.1))
# boxplot(MSE, horizontal = F, las = 2)
# abline(h = median(MSE$Bart))
# 
# # tree_size_long <- tree_size %>% gather(key = "Method", value = "MSE")
# # tree_size_long$Method <- as.factor(tree_size_long$Method)
# par(mar = c(7.1, 4.1, 4.1, 2.1))
# boxplot(tree_size, horizontal = F, las = 2)
# abline(h = median(MSE$Bart))
# 
# 
# apply(X = MSE2, MARGIN = 2, FUN = mean)
# apply(X = MSE2, MARGIN = 2, FUN = sd)
# apply(X = tree_size2, MARGIN = 2, FUN = mean)
# apply(X = tree_size2, MARGIN = 2, FUN = sd)
# 
# # MSE_long <- MSE %>% gather(key = "Method", value = "MSE")
# # MSE_long$Method <- as.factor(MSE_long$Method)
# par(mar = c(7.1, 4.1, 4.1, 2.1))
# boxplot(MSE2, horizontal = F, las = 2)
# abline(h = median(MSE2$Bart))
# 
# # tree_size_long <- tree_size %>% gather(key = "Method", value = "MSE")
# # tree_size_long$Method <- as.factor(tree_size_long$Method)
# par(mar = c(7.1, 4.1, 4.1, 2.1))
# boxplot(tree_size2, horizontal = F, las = 2)
```


```{r ECLSK_School}
course <- "ECLSK_SCHOOL"

# Baysian + Weighted
MSE_schl_bay_w <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("MSE_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)
TS_schl_bay_w <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("TreeSize_",course,"_baygen[1,5,10]_weighted")), header = TRUE, row.names = 1)

# Baysian + NOT Weighted
MSE_schl_bay <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("MSE_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)
TS_schl_bay <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("TreeSize_",course,"_baygen[1,5,10]_")), header = TRUE, row.names = 1)

# Smearing + weighted
MSE_schl_smr_w <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("MSE_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)
TS_schl_smr_w <- read.csv(file.path(here(),"Project David","ECLSK_School",paste0("TreeSize_",course,"_smearing[25%,50%]_weighted")), header = TRUE, row.names = 1)

a <- MSE_schl_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_schl_bay_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "MSE")

b <- TS_schl_bay_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_schl_bay_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + Weighted", subtitle = "Tree Size")

c <- MSE_schl_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_schl_bay)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "MSE")

d <- TS_schl_bay %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_schl_bay)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Baysian + NOT Weighted", subtitle = "Tree Size")

e <- MSE_schl_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "MSE") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(MSE_schl_smr_w)), y = MSE)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "MSE") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))

f <- TS_schl_smr_w %>% 
  pivot_longer(cols = colnames(.), names_to = "Function", values_to = "Tree_Size") %>% 
  ggplot(., aes(x = factor(Function, levels = colnames(TS_schl_smr_w)), y = Tree_Size)) +
    geom_jitter() +
    stat_summary(fun.data = mean_sdl, geom = "pointrange", color = "red") +
    xlab("") +
    labs(title = "Smearing + Weighted", subtitle = "Tree Size") +
    theme(axis.text.x = element_text(angle = -25, vjust = 0.5, hjust=0.5))


tgrob <- text_grob(course,size = 20)
plot_0 <- as_ggplot(tgrob) + theme(plot.margin = margin(0,3,0,0, "cm"))
ggarrange(NULL,plot_0,NULL,a,c,e,b,d,f, 
          labels = c("","","","A", "B", "C", "D", "E", "F"),
          ncol = 3, nrow = 3, heights = c(1,7,7))

```


